local-storage-driver:
  privileged: true
  image: nightcruisetech/local-mount:latest
  pid: host
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: environment
  environment:
    
    MOUNT_DIR: '${MOUNT_DIR}'
    MOUNT_OPTS: '${MOUNT_OPTS}'
  volumes:
  - /run:/run
  - /dev:/host/dev
  - /var/lib/rancher/volumes:/var/lib/rancher/volumes:shared
  metadata:
    storage_driver:
      name: local-storage
      scope: environment
volumeAccessMode: multiHostRW